#import "BrightcoveFeatureRegistry.h"
#import "audiotracks/BrightcoveAudioTracksFeature.h"
#import "fullscreen/BrightcoveFullscreenFeature.h"
#import "drm/BrightcoveDrmFeature.h"

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
@implementation BrightcoveFeatureRegistry

+ (NSArray<id<BrightcovePlayerFeature>> *)installedFeatures
{
  return @[
    [BrightcoveAudioTracksFeature new],
    [BrightcoveFullscreenFeature new],
    [BrightcoveDrmFeature new],
  ];
}

@end
