#import "BrightcoveFeatureRegistry.h"
#import "playlists/BrightcovePlaylistsFeature.h"
#import "fullscreen/BrightcoveFullscreenFeature.h"

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
@implementation BrightcoveFeatureRegistry

+ (NSArray<id<BrightcovePlayerFeature>> *)installedFeatures
{
  return @[
    [BrightcovePlaylistsFeature new],
    [BrightcoveFullscreenFeature new],
  ];
}

@end
