#import "BrightcoveFeatureRegistry.h"
#import "background/BrightcoveBackgroundPlaybackFeature.h"
#import "playbackevents/BrightcovePlaybackEventsFeature.h"
#import "fullscreen/BrightcoveFullscreenFeature.h"

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
@implementation BrightcoveFeatureRegistry

+ (NSArray<id<BrightcovePlayerFeature>> *)installedFeatures
{
  return @[
    [BrightcoveBackgroundPlaybackFeature new],
    [BrightcovePlaybackEventsFeature new],
    [BrightcoveFullscreenFeature new],
  ];
}

@end
