package com.brightcove.reactnativeplayer

import com.brightcove.reactnativeplayer.controls.ControlsFeature
import com.brightcove.reactnativeplayer.fullscreen.FullscreenFeature
import com.brightcove.reactnativeplayer.drm.DrmFeature
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.brightcove.reactnativeplayer.core.PlayerFeature

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
// Feature instances hold per-player state, so this is a factory (one
// registry serves every player view in the app).
object FeatureRegistry {
  fun createFeatures(): List<PlayerFeature> = listOf(
    ControlsFeature(),
    FullscreenFeature(),
    DrmFeature(),
  )

  fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> = emptyList()
  fun createReactModuleInfoProvider(): ReactModuleInfoProvider = ReactModuleInfoProvider { emptyMap() }
}
