import type { HostComponent } from 'react-native';
import { BrightcovePlayerView as FullBrightcovePlayerView } from './BrightcovePlayerView';
import type { NativeProps, NativeCommands } from './BrightcovePlayerViewNativeComponent';
import { Commands as PlayerCommandsImpl } from './BrightcovePlayerViewNativeComponent';

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
// iOS-only features are available from this platform-specific entry point.
export type BrightcovePlayerViewProps = Omit<
  NativeProps,
  | 'adTagUrl'
  | 'onAllAdsCompleted'
  | 'onAdPaused'
  | 'onAdResumed'
  | 'onAdProgress'
  | 'onAdQuartile'
  | 'onAdSkipped'
  | 'onAdInteraction'
  | 'onAdMetadata'
  | 'onAdOverlayStateChanged'
  | 'airPlayEnabled'
  | 'onExternalPlaybackChanged'
  | 'audioDescriptionEnabled'
  | 'onAudioDescriptionAvailable'
  | 'onAudioDescriptionChanged'
  | 'audioTrackId'
  | 'onAudioTracksAvailable'
  | 'onAudioTrackChanged'
  | 'backgroundPlaybackEnabled'
  | 'onRebufferStart'
  | 'onRebufferEnd'
  | 'customCaptionRenderingEnabled'
  | 'onCaptionCueChanged'
  | 'captionsEnabled'
  | 'captionTrackId'
  | 'onCaptionsAvailable'
  | 'onCaptionTrackChanged'
  | 'castEnabled'
  | 'onCastStateChanged'
  | 'chapterSeekTime'
  | 'chapterSeekRequestId'
  | 'onChapterSeekCompleted'
  | 'controlsEnabled'
  | 'daiSourceId'
  | 'daiVideoId'
  | 'freeWheelAdUrl'
  | 'freeWheelNetworkId'
  | 'freeWheelProfile'
  | 'freeWheelSiteSectionId'
  | 'freeWheelVideoAssetId'
  | 'onVideoSizeChanged'
  | 'onLiveStatus'
  | 'onSeekableRangesChanged'
  | 'offlineSourceId'
  | 'heartbeatTrackingServer'
  | 'heartbeatChannel'
  | 'heartbeatAppVersion'
  | 'heartbeatOvp'
  | 'heartbeatPlayerName'
  | 'heartbeatSsl'
  | 'heartbeatDebugLogging'
  | 'pictureInPictureEnabled'
  | 'onPictureInPictureModeChanged'
  | 'onPlay'
  | 'onPause'
  | 'onEnded'
  | 'onProgress'
  | 'videoIds'
  | 'repeatMode'
  | 'shuffle'
  | 'onQueueItemChanged'
  | 'onQueueItemFailed'
  | 'onQueueCompleted'
  | 'preloadVideoId'
  | 'onPreloadQueued'
  | 'onPreloadHandoff'
  | 'onPreloadError'
  | 'pulseHost'
  | 'pulseCategory'
  | 'pulseTags'
  | 'pulseContentMetadataTitle'
  | 'pulseMidrollPositions'
  | 'preferredPeakBitrate'
  | 'onRenditionChanged'
  | 'sidecarTracks'
  | 'onSidecarTrackStatus'
  | 'videoReferenceId'
  | 'playlistId'
  | 'playlistReferenceId'
  | 'sourceUrl'
  | 'thumbnailSeekingEnabled'
  | 'onTimedMetadata'
  | 'vrMode'
  | 'onProjectionFormatChanged'
  | 'onVideo360ModeChanged'
  | 'onAdError'
> & {
  videoId: string;
};

export const BrightcovePlayerView =
  FullBrightcovePlayerView as unknown as HostComponent<BrightcovePlayerViewProps>;

// Only the commands this copy can service (core + installed features).
export type InstalledCommands = Pick<NativeCommands, 'play' | 'pause' | 'seekTo' | 'reload' | 'enterFullscreen' | 'exitFullscreen'>;
const InstalledCommandsImpl = PlayerCommandsImpl as InstalledCommands;
export { InstalledCommandsImpl as PlayerCommands, InstalledCommandsImpl as Commands };
export const {
  play,
  pause,
  seekTo,
  reload,
  enterFullscreen,
  exitFullscreen,
} = InstalledCommandsImpl;

export type {
  PlayerCommandErrorCode,
  PlayerCommandErrorEventData,
  PlayerErrorCode,
  PlayerErrorEventData,
  ReadyEventData,
  VideoScalingMode,
  AdEventData,
  AdBreakEventData,
  AdErrorEventData,
  FullscreenChangedEventData,
} from './BrightcovePlayerViewNativeComponent';
