import { forwardRef } from 'react';
import * as ssaiIntegrationModule from '@brightcove/web-sdk/integrations/ssai';
import '@brightcove/web-sdk/integrations/ssai/styles';
import {
  BrightcovePlayerView as FullBrightcovePlayerView,
  createWebSdkPlayer,
  type BrightcovePlayerWebHandle,
  type BrightcovePlayerViewWebProps,
  type WebSdkIntegrationFactories,
  type WebSdkPlayerOptions,
} from './BrightcovePlayerView.web';

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
// The web implementation provides a truthful browser path and narrows
// its public props to the installed features of this sample.
// webControlBarComponents is always omitted here too: it is this
// generated wrapper's own fixed list below, not something the
// consuming App.tsx may override.
const WEB_INTEGRATION_FACTORIES: WebSdkIntegrationFactories = {};
WEB_INTEGRATION_FACTORIES.ssai = (
  ssaiIntegrationModule as unknown as { SsaiIntegrationFactory: unknown }
).SsaiIntegrationFactory;
const playerFactory = (options: WebSdkPlayerOptions) =>
  createWebSdkPlayer(options, WEB_INTEGRATION_FACTORIES);

export type BrightcovePlayerViewProps = Omit<
  BrightcovePlayerViewWebProps,
  | 'webControlBarComponents'
  | 'playerFactory'
  | 'captionsEnabled'
  | 'captionTrackId'
  | 'onCaptionsAvailable'
  | 'onCaptionTrackChanged'
  | 'pictureInPictureEnabled'
  | 'onPictureInPictureModeChanged'
  | 'adTagUrl'
  | 'onAllAdsCompleted'
  | 'onAdPaused'
  | 'onAdResumed'
  | 'onAdProgress'
  | 'onAdQuartile'
  | 'onAdSkipped'
  | 'onAdInteraction'
  | 'onAdMetadata'
  | 'onAdOverlayStateChanged'
  | 'onSourceLoading'
  | 'onFirstFrame'
  | 'onSeekStarted'
  | 'onSeekCompleted'
  | 'onDurationChanged'
  | 'onVideoSizeChanged'
  | 'onPlay'
  | 'onPause'
  | 'onEnded'
  | 'onProgress'
  | 'onLiveStatus'
  | 'onSeekableRangesChanged'
  | 'videoIds'
  | 'repeatMode'
  | 'onQueueItemChanged'
  | 'onQueueItemFailed'
  | 'onQueueCompleted'
  | 'onRebufferStart'
  | 'onRebufferEnd'
  | 'audioDescriptionEnabled'
  | 'onAudioDescriptionAvailable'
  | 'onAudioDescriptionChanged'
  | 'preferredPeakBitrate'
  | 'onRenditionChanged'
  | 'chapterSeekTime'
  | 'chapterSeekRequestId'
  | 'onChapterSeekCompleted'
  | 'controlsEnabled'
  | 'sidecarTracks'
  | 'onSidecarTrackStatus'
  | 'customCaptionRenderingEnabled'
  | 'onCaptionCueChanged'
  | 'daiSourceId'
  | 'daiVideoId'
  | 'audioTrackId'
  | 'onAudioTracksAvailable'
  | 'onAudioTrackChanged'
  | 'onTimedMetadata'
  | 'thumbnailSeekingEnabled'
  | 'preloadVideoId'
  | 'onPreloadQueued'
  | 'onPreloadHandoff'
  | 'onPreloadError'
>;

// The @brightcove/web-sdk/ui control-bar buttons this bridge copy
// backs, computed from its installed features
// (scripts/feature-catalog.sh feature_web_control_bar_components) so
// the control bar never shows a button (e.g. Picture-in-Picture) for
// a feature this copy never installed.
const WEB_CONTROL_BAR_COMPONENTS = [
  'PlayToggle',
  'VolumePanel',
  'CurrentTimeDisplay',
  'TimeDivider',
  'DurationDisplay',
  'ProgressControl',
  'CustomControlSpacer',
  'PlaybackRateMenuButton',
  'FullscreenToggle',
];

export const BrightcovePlayerView = forwardRef<
  BrightcovePlayerWebHandle,
  BrightcovePlayerViewProps
>(function BrightcovePlayerViewWrapper(props, ref) {
  return (
    <FullBrightcovePlayerView
      {...props}
      ref={ref}
      playerFactory={playerFactory}
      webControlBarComponents={WEB_CONTROL_BAR_COMPONENTS}
    />
  );
});

// Only the commands this copy's installed features service on web.
export const PlayerCommands = {
  play(ref: BrightcovePlayerWebHandle | null | undefined): void {
    if (!ref || typeof ref.play !== 'function') return;
    try {
      const res = ref.play();
      if (res && typeof res.catch === 'function') {
        res.catch(error => {
          console.error('[BrightcovePlayerCommands] play failed', error);
        });
      }
    } catch (error) {
      console.error('[BrightcovePlayerCommands] play failed', error);
    }
  },
  pause(ref: BrightcovePlayerWebHandle | null | undefined): void {
    if (!ref || typeof ref.pause !== 'function') return;
    try {
      ref.pause();
    } catch (error) {
      console.error('[BrightcovePlayerCommands] pause failed', error);
    }
  },
  seekTo(
    ref: BrightcovePlayerWebHandle | null | undefined,
    positionSeconds: number,
  ): void {
    if (!ref || typeof ref.seekTo !== 'function') return;
    try {
      ref.seekTo(positionSeconds);
    } catch (error) {
      console.error('[BrightcovePlayerCommands] seekTo failed', error);
    }
  },
  reload(ref: BrightcovePlayerWebHandle | null | undefined): void {
    if (!ref || typeof ref.reload !== 'function') return;
    try {
      ref.reload();
    } catch (error) {
      console.error('[BrightcovePlayerCommands] reload failed', error);
    }
  },
  enterFullscreen(ref: BrightcovePlayerWebHandle | null | undefined): void {
    if (!ref || typeof ref.enterFullscreen !== 'function') return;
    try {
      const res = ref.enterFullscreen();
      if (res && typeof res.catch === 'function') {
        res.catch(error => {
          console.error('[BrightcovePlayerCommands] enterFullscreen failed', error);
        });
      }
    } catch (error) {
      console.error('[BrightcovePlayerCommands] enterFullscreen failed', error);
    }
  },
  exitFullscreen(ref: BrightcovePlayerWebHandle | null | undefined): void {
    if (!ref || typeof ref.exitFullscreen !== 'function') return;
    try {
      const res = ref.exitFullscreen();
      if (res && typeof res.catch === 'function') {
        res.catch(error => {
          console.error('[BrightcovePlayerCommands] exitFullscreen failed', error);
        });
      }
    } catch (error) {
      console.error('[BrightcovePlayerCommands] exitFullscreen failed', error);
    }
  },
};

export const Commands = PlayerCommands;

export type {
  PlayerCommandErrorCode,
  PlayerCommandErrorEventData,
  PlayerErrorCode,
  PlayerErrorEventData,
  ReadyEventData,
  VideoScalingMode,
  AdEventData,
  AdBreakEventData,
  AdErrorEventData,
  FullscreenChangedEventData,
} from './webErrorClassification';

export interface NativeCommands {
  play: (viewRef: unknown) => void;
  pause: (viewRef: unknown) => void;
  seekTo: (viewRef: unknown, positionSeconds: number) => void;
  reload: (viewRef: unknown) => void;
  enterFullscreen: (viewRef: unknown) => void;
  exitFullscreen: (viewRef: unknown) => void;
}
