package com.brightcove.reactnativeplayer

import com.brightcove.reactnativeplayer.offline.BrightcoveOfflinePlaybackFeature
import com.brightcove.reactnativeplayer.fullscreen.FullscreenFeature
import com.brightcove.reactnativeplayer.offline.BrightcoveOfflinePlaybackModule
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.module.model.ReactModuleInfo
import com.brightcove.reactnativeplayer.core.PlayerFeature

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
// Feature instances hold per-player state, so this is a factory (one
// registry serves every player view in the app).
object FeatureRegistry {
  fun createFeatures(): List<PlayerFeature> = listOf(
    BrightcoveOfflinePlaybackFeature(),
    FullscreenFeature(),
  )

  fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> = listOf(
    BrightcoveOfflinePlaybackModule(reactContext),
  )

  fun createReactModuleInfoProvider(): ReactModuleInfoProvider {
    val moduleClasses = arrayOf<Class<out NativeModule>>(
      BrightcoveOfflinePlaybackModule::class.java,
    )
    val moduleInfo = mutableMapOf<String, ReactModuleInfo>()
    for (moduleClass in moduleClasses) {
      val annotation = moduleClass.getAnnotation(ReactModule::class.java) ?: continue
      moduleInfo[annotation.name] = ReactModuleInfo(
        annotation.name,
        moduleClass.name,
        true,
        annotation.needsEagerInit,
        annotation.isCxxModule,
        true,
      )
    }
    return ReactModuleInfoProvider { moduleInfo }
  }
}
