#import "BrightcoveFeatureRegistry.h"
#import "offline/BrightcoveOfflinePlaybackFeature.h"
#import "fullscreen/BrightcoveFullscreenFeature.h"

// Generated by scripts/assemble-bridge.sh. Do not edit by hand.
@implementation BrightcoveFeatureRegistry

+ (NSArray<id<BrightcovePlayerFeature>> *)installedFeatures
{
  return @[
    [BrightcoveOfflinePlaybackFeature new],
    [BrightcoveFullscreenFeature new],
  ];
}

@end
